### ISSUE TITLE
Cannot use sct with mechanic/boontable

### ISSUE THREAD

**Issue by nodoooka** [Artenuvielle/GW2-SCT#2] opened 2018-12-01 04:04 UTC
Cannot drag the pannel of boontable when use act.
Cannot load correct fonts of boontable.
http://martionlabs.com/arcdps-mechanics-log-plugin/
![qq 20181201120411](https://user-images.githubusercontent.com/44370486/49324060-3b47e380-f561-11e8-90df-1a9a495019e8.jpg)

**Comment by nodoooka** [comment] 2018-12-01 10:51
The boon table cannot load my own font with  the latest dev version as well, but sct options can.

**Comment by nodoooka** [comment] 2018-12-01 10:53
![qq 20181201185320](https://user-images.githubusercontent.com/44370486/49327268-6d296c00-f59a-11e8-916e-93b910cb5a12.jpg)

**Comment by Artenuvielle** [comment] 2018-12-01 14:15
I'll try to reproduce this and have a look into it later in the coming week.

**Comment by jiangyi0923** [comment] 2018-12-05 06:01
Nodoooka He made the Chinese version of Marion Laboratories' Boon Table, but because he doesn't have the source code, he replaces it with a binary, but there is a problem with your sct coexistence.
If you don't use sct, Martion Laboratories' Boon Table can load fonts normally. If you use sct, Boon Table can't load fonts normally. The same is true with the #1 local version of sct. I think there may be a problem with "calling", or It is reassigned

**Closed** 2021-03-01 06:52 UTC
