### ISSUE TITLE
of skill icon bug

### ISSUE THREAD

**Issue by jiangyi0923** [Artenuvielle/GW2-SCT#11] opened 2020-03-27 10:56 UTC
1.After enabling the skill icon, the game client cannot be closed normally,Will be blocked when the exit button is clicked
2.and Sometimes, the client ends the game for no reason,
bug 2 It also existed in version 1.1,and bug1 is new.
Maybe your image download code needs more reasonable modification

**Comment by Artenuvielle** [comment] 2020-03-27 10:59
Can you provide an SCT log file for both of these cases. they are located at 'GW2 dir\addons\sct\sct.log'.

**Comment by jiangyi0923** [comment] 2020-03-27 11:02
Perhaps bug 1 problem was that it ended the client without a smooth release of some memory or other ,The log is on my laptop pc, I can't provide it to you for the moment

**Comment by jiangyi0923** [comment] 2020-03-27 11:13
[bug2.zip](https://github.com/Artenuvielle/GW2-SCT/files/4393055/bug2.zip)

**Comment by Artenuvielle** [comment] 2020-03-30 13:05
Sadly I cannot reproduce any of these issues. I also checked compatibility with other addons and everything else than dx912pxy should go well with SCT.

**Comment by Artenuvielle** [comment] 2020-03-30 15:01
The skill icon loading function did change slightly in version 1.2-RC3. Check it out and feel free to tell me if it resolved any issues.

**Comment by jiangyi0923** [comment] 2020-03-30 15:31
im chinese player ,maybe also the reason for these bugs,After using r3, the problem still exists. Here is the screenshot.
![QQ截图20200330232607](https://user-images.githubusercontent.com/40364405/77931341-a123b700-72de-11ea-946e-d3e85ef2dcf4.png)

Perhaps, the Chinese web access to wiki is slow reason

**Comment by jiangyi0923** [comment] 2020-03-30 15:33
and log is
GW2 SCT: loading: C:\jz2\addons\sct\fonts\arcdps_font.ttf
GW2 SCT: loading: C:\jz2\addons\sct\fonts\Roboto-Regular.ttf
GW2 SCT: Running arcvers: 20200325.120355-323-x64
GW2 SCT: Skillicon load thread started
GW2 SCT: Downloading skill icon: 10285
GW2 SCT: Downloading skill icon: 10191
GW2 SCT: Skillicon load thread stopping

**Comment by jiangyi0923** [comment] 2020-03-30 15:51
Try to enter the game and then exit the game a few times.  It's better than the first edition, but clicking the exit button still takes a few seconds

**Comment by Artenuvielle** [comment] 2020-03-31 18:23
Yeah I guess you icon download is kinda slow from the official rendering API. If a download is still ongoing then the skill icon download thread won't stop until its current download is finished. I guess when you exit the game you'd have to wait for the current ongoing download to finish and only the game exits completely.

Maybe this does not happen when you already provide all of the available icons in the /addons/sct/icons folder. I added a folder with every icon I downloaded just a couple of days ago.
[icons.zip](https://github.com/Artenuvielle/GW2-SCT/files/4410579/icons.zip)

**Comment by jiangyi0923** [comment] 2020-04-02 13:17
It doesn't work properly. When I open the skill icon, I will exit the game in a few minutes.Can you directly localize the skill icon for the Chinese version?

**Comment by Artenuvielle** [comment] 2020-04-02 13:57
Can you explain in more detail what you mean?

**Comment by jiangyi0923** [comment] 2020-04-02 15:22
您可以尝试编译一个完全从“图标”文件夹加载的技能图标版本。让我来测试一下，是API连接问题，还是图片加载问题，还是内存泄漏

**Comment by jiangyi0923** [comment] 2020-04-02 15:22
You can try to compile a version of the skill icon that loads completely from the "icon" folder. Let me test it out,Was it an API connection problem or a picture load problem or a memory leak

**Comment by jiangyi0923** [comment] 2020-04-02 15:33
This situation of quitting the game, after opening the skill icon option, I will quit the game directly within a few minutes regardless of whether I use the skill or not, which makes me feel uneasy to share it with Chinese players. If this problem occurs frequently on my computer, can you imagine what other players will think,Perhaps the only thing you can do now is  load  the images localize

**Comment by jiangyi0923** [comment] 2020-04-03 05:58
In version 1.3, even if there is a skill picture in the "icon" folder, the picture will still be downloaded once, which causes unnecessary downloading thread. There is no strange flash back half an hour after the skill icon is started, but the game will still be blocked

**Comment by Artenuvielle** [comment] 2020-04-03 06:52
Yeah, I'll have a look into it in a couple of days.

**Comment by Enko63** [comment] 2020-04-12 20:01
Looks like Anet's APIs are down atm too. 
Is there a way to use skill icons but not download new ones and they just won't show up if its not there?

**Comment by jiangyi0923** [comment] 2020-04-13 12:14
I used this multithreaded library void for my project:

> boost::thread thread_(void, pass parameter);

I hope it can help you,

**Comment by Artenuvielle** [comment] 2021-03-01 06:51
Crashes with skill icons *should* be fixed in 1.3RC4

**Closed by Artenuvielle** 2021-03-01 06:51 UTC
